# Generated by Django 6.0.2 on 2026-04-09 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='items/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Collected', 'Not Collected'), ('Collected', 'Collected')], default='Not Collected', max_length=20)),
                ('submission_type', models.CharField(choices=[('desk', 'Submitted to Lost & Found Desk'), ('finder', 'Kept with Finder')], max_length=20)),
                ('submitted_at', models.CharField(blank=True, choices=[('SAS', 'School of Arts and Sciences'), ('GICT', 'GICT Building'), ('UC', 'University Center'), ('BK', 'BK School Area')], max_length=10, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('audio_blob', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_transcript', models.TextField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('enrollment_number', models.CharField(max_length=20, verbose_name='Enrollment Number')),
                ('subject', models.CharField(default='General Complaint', max_length=200)),
                ('category', models.CharField(choices=[('lost_item', 'Lost Item Not Listed'), ('found_item', 'Found Item Issue'), ('staff', 'Staff Behaviour'), ('process', 'Process/System Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('staff_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='items.item')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimer_name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('au_email', models.EmailField(max_length=254)),
                ('id_card_photo', models.ImageField(upload_to='claims/')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('filled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_filled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
        ),
    ]
